// <auto-generated />
namespace Samurai.SqlDataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class some_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(some_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201306261122088_some_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
