// <auto-generated />
namespace Samurai.SqlDataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addinplaytomatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinplaytomatch));
        
        string IMigrationMetadata.Id
        {
            get { return "201301200954586_add-inplay-to-match"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
